tunnel: fc684959-05b6-4f5c-aca6-b87ccadec4c3
credentials-file: credentials.json

ingress:
  - hostname: api-youtubetiktok.neocodigox.com
    service: http://localhost:8000
  - service: http_status:404
